//All Rights Reserved.
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// XML Revision      : $Revision: 1.238 $
//
//---------------------------------------------------------------------------------------------------------------


// Block1 hierarchy

//  Block1

module Block1
    (
    
    input   hresetn,
    input   hclk,
    output  Reg11_enb,
    output  [15:0]Reg11_F_r,
    input   [15:0]Reg11_F_in,
    input   Reg11_F_in_enb,
    output  Reg12_enb,
    input   [31:0]Reg12_F_r,
    // amba_widget;
    output  [31:0]hrdata,
    output  [1:0]hresp,
    input   [1:0]htrans,
    input   [3:0]haddr,
    input   hwrite,
    input   [2:0]hsize,
    input   [3:0]hprot,
    input   [31:0]hwdata,
    input   hsel,
    input   [2:0]hburst,
    output  hready
    );
    amba_widget amba_widget(.hrdata (hrdata[31:0]),
    .hresp (hresp[1:0]),
    .htrans (htrans[1:0]),
    .haddr (haddr[3:0]),
    .hwrite (hwrite),
    .hsize (hsize[2:0]),
    .hprot (hprot[3:0]),
    .hwdata (hwdata[31:0]),
    .hsel (hsel),
    .hburst (hburst[2:0]),
    .hready (hready)
    
    );
    
    
    
    
    
    
endmodule

