--All Rights Reserved.
--
--*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
-- XML Revision      : $Revision: 1.142 $
--
-----------------------------------------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
--use IEEE.STD_LOGIC_UNSIGNED.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;

--
--  Block1 hierarchy
--
--  Block1
--

--




entity Block1 is
    
    port (
        
        -- amba_widget;
        hrdata    : out   std_logic_vector(31 downto 0);
        hresp     : out   std_logic_vector(1 downto 0);
        htrans    : in    std_logic_vector(1 downto 0);
        haddr     : in    std_logic_vector(3 downto 0);
        hwrite    : in    std_logic;
        hsize     : in    std_logic_vector(2 downto 0);
        hprot     : in    std_logic_vector(3 downto 0);
        hwdata    : in    std_logic_vector(31 downto 0);
        hsel      : in    std_logic;
        hburst    : in    std_logic_vector(2 downto 0);
        hready    : out   std_logic;
        
        -- Ports
        hresetn   : in    std_logic;
        hclk      : in    std_logic;
        Reg11_enb : out   std_logic;
        Reg11_F_r : out   std_logic_vector(15 downto 0);
        Reg11_F_in : in    std_logic_vector(15 downto 0);
        Reg11_F_in_enb : in    std_logic;
        Reg12_enb : out   std_logic;
        Reg12_F_r : in    std_logic_vector(31 downto 0)
        
    );
    
end  Block1;


-------------------------------------------------------------
-- ARCHITECTURE : Block1 ENTITY
-------------------------------------------------------------


architecture rtl of Block1 is
    
    begin
        
        amba_widget: entity work.amba_widget
        
        port map (
            hrdata => hrdata,
            hresp => hresp,
            htrans => htrans,
            haddr => haddr,
            hwrite => hwrite,
            hsize => hsize,
            hprot => hprot,
            hwdata => hwdata,
            hsel => hsel,
            hburst => hburst,
            hready => hready
            
        );
        
        
        
        
    end rtl;
    
    
