--All Rights Reserved.
--
--*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
-- XML Revision      : $Revision: 1.142 $
--
-----------------------------------------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
--use IEEE.STD_LOGIC_UNSIGNED.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;

--
--  timers hierarchy
--
--  timers
--

--




entity timers is
    
    generic (
        
        TPRESC :  integer := 22        --EXAMPLE TO SHOW, HOW TO WRITE PARAMETERS.
    );
    
    port (
        
        -- ambaAPB;
        psel      : in    std_logic;
        penable   : in    std_logic;
        paddr     : in    std_logic_vector(31 downto 0);
        pwrite    : in    std_logic;
        pwdata    : in    std_logic_vector(31 downto 0);
        prdata    : out   std_logic_vector(31 downto 0);
        irq0      : out   std_logic;
        irq1      : out   std_logic;
        
        -- Ports
        clk       : in    std_logic;
        rst       : in    std_logic;
        tick      : out   std_logic;
        wdog      : out   std_logic;
        dsuact    : in    std_logic;
        ntrace    : in    std_logic;
        freezetime : in    std_logic;
        lresp     : in    std_logic;
        dresp     : in    std_logic_vector(1 downto 0);
        dsuen     : in    std_logic;
        dsubre    : in    std_logic
        
    );
    
end  timers;


-------------------------------------------------------------
-- ARCHITECTURE : timers ENTITY
-------------------------------------------------------------


architecture rtl of timers is
    
    begin
        
        ambaAPB: entity work.APB_rtl
        
        port map (
            PSELx => psel,
            PENABLE => penable,
            PADDR => paddr,
            PWRITE => pwrite,
            PWDATA => pwdata,
            PRDATA => prdata
            
        );
        
        
        
        
    end rtl;
    
    
