//All Rights Reserved.
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// XML Revision      : $Revision: 1.238 $
//
//---------------------------------------------------------------------------------------------------------------


// timers hierarchy

//  timers

module timers
    #( parameter
    TPRESC = 22        //EXAMPLE TO SHOW, HOW TO WRITE PARAMETERS.
    )
    
    (
    
    input   clk,
    input   rst,
    output  tick,
    output  wdog,
    input   dsuact,
    input   ntrace,
    input   freezetime,
    input   lresp,
    input   [1:0]dresp,
    input   dsuen,
    input   dsubre,
    // ambaAPB;
    input   psel,
    input   penable,
    input   [31:0]paddr,
    input   pwrite,
    input   [31:0]pwdata,
    output  [31:0]prdata,
    // Int0;
    output  irq0,
    // Int1;
    output  irq1
    );
    APB_rtl ambaAPB(.PSELx (psel),
    .PENABLE (penable),
    .PADDR (paddr),
    .PWRITE (pwrite),
    .PWDATA (pwdata),
    .PRDATA (prdata)
    
    );
    
    
    
    
    
    
endmodule

