//All Rights Reserved.
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// XML Revision      : $Revision: 1.238 $
//
//---------------------------------------------------------------------------------------------------------------


// apbSubSystem hierarchy

//  apbSubSystem

module apbSubSystem
    (
    
    input   clk,
    input   rst_an,
    output  [3:0]Interrupt_IRL,
    input   [3:0]Interrupt_IRQVEC,
    input   Interrupt_INTack,
    input   ex_ambaAHB_hsel,
    output  ex_ambaAHB_hready_resp,
    output  [31:0]ex_ambaAHB_hrdata,
    input   [3:0]ex_ambaAHB_hprot,
    input   [1:0]ex_ambaAHB_htrans,
    input   [2:0]ex_ambaAHB_hsize,
    input   ex_ambaAHB_hready,
    input   ex_ambaAHB_hwrite,
    input   [2:0]ex_ambaAHB_hburst,
    input   [31:0]ex_ambaAHB_haddr,
    output  [1:0]ex_ambaAHB_hresp,
    input   [31:0]ex_ambaAHB_hwdata,
    output  [31:0]i_apbbus_slv4_paddr,
    output  i_apbbus_slv4_psel,
    output  i_apbbus_slv4_pwrite,
    output  [31:0]i_apbbus_slv4_pwdata,
    output  i_apbbus_slv4_penable,
    input   [31:0]i_apbbus_slv4_prdata,
    output  [31:0]i_apbbus_slv5_paddr,
    output  i_apbbus_slv5_psel,
    output  i_apbbus_slv5_pwrite,
    output  [31:0]i_apbbus_slv5_pwdata,
    output  i_apbbus_slv5_penable,
    input   [31:0]i_apbbus_slv5_prdata,
    output  [31:0]i_apbbus_slv6_paddr,
    output  i_apbbus_slv6_psel,
    output  i_apbbus_slv6_pwrite,
    output  [31:0]i_apbbus_slv6_pwdata,
    output  i_apbbus_slv6_penable,
    input   [31:0]i_apbbus_slv6_prdata,
    output  [31:0]i_apbbus_slv7_paddr,
    output  i_apbbus_slv7_psel,
    output  i_apbbus_slv7_pwrite,
    output  [31:0]i_apbbus_slv7_pwdata,
    output  i_apbbus_slv7_penable,
    input   [31:0]i_apbbus_slv7_prdata
    );
    
    
    
    
    
endmodule

