//All Rights Reserved.
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// XML Revision      : $Revision: 1.238 $
//
//---------------------------------------------------------------------------------------------------------------


// uart hierarchy

//  uart

module uart
    #( parameter
    EXTBAUD = FALSE        //EXAMPLE TO SHOW, HOW TO WRITE PARAMETERS.
    )
    
    (
    
    input   [9:0]scaler,
    output  txen,
    output  flow_MeeXXTTI,
    // APBClk;
    input   clk,
    // APBReset;
    input   rst,
    // ambaAPB;
    input   psel,
    input   penable,
    input   [31:0]paddr,
    input   pwrite,
    input   [31:0]pwdata,
    output  [31:0]prdata,
    // Interrupt;
    output  irq,
    // serial;
    input   rxd,
    output  txd,
    input   ctsn,
    output  rtsn,
    output  rxen
    );
    
    
    
    
    
endmodule

