--All Rights Reserved.
--
--*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
-- XML Revision      : $Revision: 1.142 $
--
-----------------------------------------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
--use IEEE.STD_LOGIC_UNSIGNED.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;

--
--  block2 hierarchy
--
--  block2
--

--




entity block2 is
    
    generic (
        
        bus_width :  integer := 32;
        addr_width :  integer := 3;
        block_offset :  integer := 0;
        reg_groupA_count :  integer := 1;
        reg_groupA_address_width :  integer := 3
    );
    
    port (
        
        -- amba_widget;
        hresetn   : in    std_logic;
        hclk      : in    std_logic;
        hrdata    : out   std_logic_vector(31 downto 0);
        hresp     : out   std_logic_vector(1 downto 0);
        htrans    : in    std_logic_vector(1 downto 0);
        haddr     : in    std_logic_vector(2 downto 0);
        hwrite    : in    std_logic;
        hsize     : in    std_logic_vector(7 downto 0);
        hprot     : in    std_logic_vector(3 downto 0);
        hwdata    : in    std_logic_vector(31 downto 0);
        hsel      : in    std_logic;
        hburst    : in    std_logic_vector(2 downto 0);
        hready    : out   std_logic;
        
        -- Ports
        Reg1_enb  : out   std_logic;
        Reg1_F_in : in    std_logic_vector(31 downto 0);
        Reg1_F_in_enb : in    std_logic;
        Reg1_F_r  : out   std_logic_vector(31 downto 0);
        Reg2_F_in : in    std_logic_vector(7 downto 0);
        Reg2_F_in_enb : in    std_logic;
        Reg2_F_r  : out   std_logic_vector(15 downto 0)
        
    );
    
end  block2;


-------------------------------------------------------------
-- ARCHITECTURE : block2 ENTITY
-------------------------------------------------------------


architecture rtl of block2 is
    
    begin
        
        amba_widget: entity work.amba_widget
        
        port map (
            hresetn => hresetn,
            hclk => hclk,
            hrdata => hrdata,
            hresp => hresp,
            htrans => htrans,
            haddr => haddr,
            hwrite => hwrite,
            hsize => hsize,
            hprot => hprot,
            hwdata => hwdata,
            hsel => hsel,
            hburst => hburst,
            hready => hready
            
        );
        
        
        
        
    end rtl;
    
    
